### ISSUE TITLE
The issue resolved? 

### ISSUE THREAD

**Issue by lqjack** [stevehu/server2server#1]

**Comment by lqjack** [comment]
Hi , I have encountered the same issue. Do you have resolve the issue util now . thanks .

**Comment by stevehu** [comment]
This example was created one year ago. Since then, we have created Http2Client of our own and using it for the server to server communication with client-side discovery. 

Here is a tutorial that might help. https://doc.networknt.com/tutorial/common/discovery/

**Comment by stevehu** [comment]
I will remove this repository because it makes users confused.

**Comment by lqjack** [comment]
Thanks very much.

**Comment by lqjack** [comment]
From my understanding , the issue should be the channel closed.  why do you just implement your client ?

**Comment by stevehu** [comment]
This repo is just one of the tests I use and not supposed to be published. All public repos are in [networknt](https://github.com/networknt) and [taiji-chain](https://github.com/taiji-chain) organizations.
